name: the_eye_of_the_world
description: "the eye of the world"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.0
  logger: ^2.5.0
  flutter_bloc: ^9.1.0
  gap: ^3.0.1
  get_it: ^8.0.3
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  advertising_id: ^2.7.1
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - assets/json/
     - assets/audio/

  fonts:
      - family: Jersey25
        fonts:
          - asset: assets/fonts/Jersey25-Regular.ttf
      - family: Orbitron
        fonts:
          - asset: assets/fonts/Orbitron-Regular.ttf


